#!/bin/bash
if [ -z "$1" ]; then 
  echo usage: $0 testNumber jvmName
  exit
 fi
java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=config/dcvm.policy \
     fr.sorbonne_u.cps.pubsub.demo.DemoTimedDistributed $1 config/config.xml